### ISSUE TITLE
实现在Flutter Web中嵌入codemirror - Kingtous的博客 | Kingtous' Blog

### ISSUE THREAD

**Issue by Kingtous** [Kingtous/Kingtous.github.io#34]
https://kingtous.cn/2020/04/13/%E5%AE%9E%E7%8E%B0%E5%9C%A8Flutter-Web%E4%B8%AD%E5%B5%8C%E5%85%A5codemirror/

**Comment by Kingtous** [comment]
`空格`和`Tab按键`感觉可以通过`RawKeyBoardListener`强制`focus`和原生<scripts>屏蔽来解决。
```javascript
<script>
    document.onkeydown = function (t) {
        if(t.which == 9){
        return false;
        }
    }
</script>
```
但是感觉这个方案还是不行

**Comment by vmmc2** [comment]
您能否提供有关此函数 showCodeEditor 的进一步说明？我不明白它应该如何工作。对不起，我的中文不好。我不太流利。

**Comment by vmmc2** [comment]
我忘了在前一条评论中提到一件事。我正在使用Codemirror进行工作的FlutterWebApp，但是在理解应如何实施方面遇到了麻烦。您能帮我解决这个问题吗？可能通过电子邮件或其他某种形式的通信。感谢您的时间和耐心等待。

**Comment by Kingtous** [comment]
我在我的代码中没有找到showCodeMirror函数，你想说的是不是buildCodeMirror？
I didn't find any funtion named `showCodeMirror` but `buildCodeMirror`？
如果你想说的是buildCodeMirror函数的话，我可以解释一下：
 I can talk about the idea which corresponds to the code. The explanation of the funtion `buildCodeMirror` shows below：
在Flutter中使用HtmlElementView可以嵌入一个htmlelement。htmlelement可以对应一个div元素。而CodeMirror插件可以填充入我们的div元素中。但是填充后，这个htmlelement内部是个shadowroot结构，外部的css header对shadowroot内部的元素没有任何影响，所以我们要想办法将css引用进shadowroot结构。所以我在DOM中全局搜索到`flt-platform-view`（目前Flutter官方说只能这能获取），拿到shadowroot根结点，往里面添加headElement，内部填入css header以及必要的javascript。
HtmlElementView in Flutter can embed an htmlelement. htmlelement can correspond to a div element in html. The CodeMirror plugin can be filled into our div element. But after filling, u can find this codemirror is inside a shadowroot structure(a html structure). The external css header has no effect on the elements inside the shadowroot, so we have to find a way to reference the css into the shadowroot structure. So I searched for `flt-platform-view` in the DOM globally (currently Flutter officially says it can only be obtained by this way), get the shadowroot root node, add headElement to it, fill in the css header and necessary javascript inside.
我也是花了很多时间，使用Chrome的console功能一步步试出来的，希望这个解释对你有所帮助。
I spent a lot of time trying it out step by step using Chrome's Console and I really hope this explanation will help you.

**Comment by vmmc2** [comment]
我要感谢您的时间和耐心，并表示我很抱歉花了这么长时间回答。这周我遇到了一些问题。
无论如何，非常感谢您的解释，它清除了我第一次在您的页面中看到该帖子时无法理解的几点。
但是，我仍然对您如何做到这一点有疑问。
首先，我之前提到的函数名称为“ showCodeEditor”。您可以在教程的第三步中使用它。更具体地说，您可以在FlatButton小部件内将其作为NamedParameter传递。我不了解该怎么做，也没有在本教程中找到其实现。您能否再多谈一点？
我了解您在之前的步骤中所做的选择，例如变量'_codeMirrorId，_codeContent，_codeMirror，_codeView，OPTIONS'。我也了解使用小部件嵌入HtmlElement的想法。
我的第二个疑问是：我应该在StateObject中声明所有这些变量吗？
继续前进，我了解您在4.1和4.2节中所做的事情，但是我不确定应在StatefulWidget的哪一部分放置这些代码行。我将其放在initState（）函数中。那是对的吗？
最后，在第4.3节中，您说您将使用名为“ cdn.bootcss.com”的网站上的一些CSS和JS文件。我试图访问该页面，但由于收到403而无法访问： ForbiddenError。因此，我无法使用您在后续步骤中提到的Html文件，但是我被卡住了。老实说，我不是Html，CSS和JS的专家，所以我并不完全了解本章如果您可以更详细地解释这些步骤，或者如果您共享了该教程的全部代码，我将不胜感激。

**Comment by Kingtous** [comment]
我的代码用在了我一个开源项目中：[coding_page.dart](https://github.com/Kingtous/Flutter-CodeRunningWeb/blob/master/lib/business/user/dashboard/modules/code/coding_page.dart)，[code_editor.dart](https://github.com/Kingtous/Flutter-CodeRunningWeb/blob/master/lib/ui/code_editor.dart)
里面有完整代码且做了封装，你可以参考

> u can check [coding_page.dart in Flutter-CodeRunningWeb](https://github.com/Kingtous/Flutter-CodeRunningWeb/blob/master/lib/business/user/dashboard/modules/code/coding_page.dart)，[code_editor.dart](https://github.com/Kingtous/Flutter-CodeRunningWeb/blob/master/lib/ui/code_editor.dart) for full codes

另外`cdn.bootcss.com`网站域名确实好像被弃用了，后缀换成了`.net`，你可以参考 [BootCDN CodeMirror](https://www.bootcdn.cn/codemirror/)，但是这是个中国网站，可能在你那里会显示`403 forbidden`，你可以换成`CodeMirror`官网上的CSS和JS文件

> In addition, the domain name of the cdn.bootcss.com website does seem to be deprecated. The suffix is replaced by .net. You can refer to BootCDN CodeMirror, but this is a Chinese website. It may display 403 forbidden or timeout in your place. You can change them to CSS and JS files which are  from the CodeMirror official website.

**Comment by vmmc2** [comment]
非常感谢 我将研究提供的文件。 您提到的这些CSS和JS文件...如何在项目中链接它们？ 当我启动Flutter Web项目时，它将位于创建的Web文件夹内吗？

**Comment by Kingtous** [comment]
放在assets文件夹里面就可以了，使用Flutter提供的rootBundle类读取
> just place into assets folders. use rootBundle class to get its content.

**Comment by vmmc2** [comment]
您好，抱歉再次打扰您。我能够将您创建的Editor Widget集成到项目中（非常感谢）。但是，我很难获得在Widget编辑器中编写的内容。我查看了您项目的代码，但没有找到任何可以帮助我的东西。您能告诉我在这种情况下如何进行吗？感激不尽

**Comment by Kingtous** [comment]
see [coding_page.dart](https://github.com/Kingtous/Flutter-CodeRunningWeb/blob/52684165945410ff91b9174ac9ea870b605212e0/lib/business/user/dashboard/modules/code/coding_page.dart) for more detail.
